org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=armedstands
mod.name=Armed Stands
mod.group=net.tschipcraft
mod.version=1.0
mod.channel_tag=
mod.authors=Tschipcraft
mod.contributors=Fyoncle
mod.license=Custom
mod.description=Gives all armor stands arms by default. The arms can be toggled individually by shift-right-clicking an armor stand.
mod.sources_url=https://github.com/Tschipcraft/armedstands
mod.issues_url=https://github.com/Tschipcraft/armedstands/issues
mod.homepage_url=https://modrinth.com/project/9qYoL1rO
mod.donate_url=https://ko-fi.com/tschipcraft
mod.youtube_url=https://www.youtube.com/@tschipcraft
#mod.discord_url= No discord atm

deps.minecraft=[VERSIONED]
deps.minecraft_range=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.fabric_api_range=*
deps.fabric_loader_range=*

publish.modrinth=9qYoL1rO
publish.curseforge=1483685
publish.curseforge_slug=armed-stands
publish.github=true
